sudo: false

language: "node_js"

jobs:
  include:
    - stage: test
      node_js: lts/*
# Uncomment to modify test script (default: npm test)
#       script:
#         - npm run lint
#         - "./setup.test.sh"
# Uncomment to publish to npm
#     - stage: release
#       if: branch = master
#       node_js: lts/*
#       script: skip
#       deploy:
#         provider: script
#         skip_cleanup: true
#         script:
#           - npx semantic-release

notifications:
  slack:
    rooms:
      secure: WV642pXgCwomsKHu1+7vOKPszkSPL3z49lDlM+xDY9zF7/EXI7LoxeY+uRfGQUZNku6OLeO2GUjiCeye8NbzHcPkQUIJzH3CdL+lqBCcZDY4qvs03LJ5WzaxNNW0SJeWcAl37aBVdO6okuGjLPcgx5LPvpDSOQoNfKF0GdADnnrjUcRbYSZ38iXyzpV/kaLi0V7N8tIcDruZY7hbkTKDalDhG8Zj59uJLGbxqNoBtON1FRtozLjVowBeXBsV2RZN5ueKyM/M8YLIyMPFxLa+OucgIhrGTLKo4alIMy6KYCy60o0WUOQ9+MfQzYOKQ07Vppd0hO7wYzPeeQ/cQJgOgA0oe/dHibXR/bNJh3a2WCIGCNAOcTgxo/0Y/t4jQ9NkTVFUVTX862hLaOPmCCKcbFajJbUHl8ix8M9D4jmGWcwghK1iPAQ9mZJZ6Q1SM9U4f148NVaoUPOcW1HEjUFSpd2+pHnW7l12cocbJMjKvJe31n08eotRNOlQxMCQXpr6+rMwKqZgMFbazMSZd6L6vJCphVtFq1UnwnNnbj+131XStBq9YAFfskZO+TPj6bqTS5tV7LJEdEOk1L2ilvSq3+9OAfcT+iSRgyGWAdAklZXG47zZis14b/08ttO1aXuDtOpGvLtUN+rimhG9JWiLcWqWdxSw6ueeontuqQbvRcg=
    template:
      - "Build <%{build_url}|%{result}> for %{repository_slug}@%{branch} (<%{compare_url}|%{commit}>) in %{duration}"
    on_success: change
    on_failure: always
